### ISSUE TITLE
Can I increase the max size of the tmp drive?

### ISSUE THREAD

**Issue by zhouhao27** [imothee/tmpdisk#10]
Can I increase the max size of the tmp drive? Thanks.

**Comment by imothee** [comment]
Yes, there's no theoretical limit if you choose advanced mode. Advanced mode lets you enter any size in MB (as long as you have enough free ram).

<img width="408" alt="screen shot 2017-08-03 at 6 26 57 pm" src="https://user-images.githubusercontent.com/574560/28950533-7b8fe782-7879-11e7-843d-2701c2037954.png">
<img width="410" alt="screen shot 2017-08-03 at 6 27 09 pm" src="https://user-images.githubusercontent.com/574560/28950535-7cca40e8-7879-11e7-8c7b-a66f3f71160e.png">

**Comment by imothee** [comment]
Closing this as answered.
