### ISSUE TITLE
Feature request: Edit existing TmpDisk

### ISSUE THREAD

**Issue by simongcc** [imothee/tmpdisk#12]
Thanks for the great work!
It saves not only time but also save the SSD from being rewritten unnecessarily.

I can see that there are 2 icons in the save tmpdisk with Eject and Refresh.
Is it possible to edit the existing ramdrive?
Because in my scenario, I would like to add some more auto create folders when it is being created.
So an edit feature would be nice.

Many thanks again.

**Comment by imothee** [comment]
I've made changes to the autocreate manager in 2.0 so you can edit all the aspects of an AutoCreated disk. It's in alpha if you want to try it out.
