### ISSUE TITLE
Feature Request: Warn if items exist on RAM Disk before shutdown/eject

### ISSUE THREAD

**Issue by mgmhunt** [imothee/tmpdisk#13]
Possible to add a 'Are you sure?' option if there are items on the RAM disk, before quitting etc?

(Thanks for the app!)

**Comment by imothee** [comment]
@mgmhunt sorry, just getting to cleanup old issues and I missed this one. Are you thinking about this on ejecting the disk vs quitting the app (since quitting doesn't remove the tmpdisk).

I can add a confirm dialog on eject.

**Comment by mgmhunt** [comment]
Wow quite an old idea... can't really remember!  But I'd say because I occasionally use the RAM disk as a temp rendering space or scratch disk, just a prompt before ejecting would be good as it should remind the user the items will be erased permanently and also potentially cause applications to crash who are using that disk...

Anyway the 'confirm dialog on eject' sounds like a good option to add (?!) (maybe only if files other than the hidden system folders are on there ie anything other than initial state on system load).

**Comment by imothee** [comment]
This has been added in 2.0, thanks for the suggestion.
