### ISSUE TITLE
Feature Request: Use mount_tmpfs where supported

### ISSUE THREAD

**Issue by TwentyFourD** [imothee/tmpdisk#14]
I've discovered that mount_tmpfs was recently added to MacOS. Doing "man mount_tmpfs" says it was added in 10.16 so I've been able to use it manually in Big Sur. It would be great to have it integrated into tmpdisk so that there is a handy GUI to create a tmpfs volume on login.

**Comment by imothee** [comment]
Hi @TwentyFourD - I haven't been actively maintaining tmpdisk for a while but do you know the benefits of using tmpfs vs mounting a standard filesystem on the ram?

I looked and found
A tmpfs filesystem has the following properties:

       *  The filesystem can employ swap space when physical memory
          pressure demands it.

       *  The filesystem consumes only as much physical memory and swap
          space as is required to store the current contents of the
          filesystem.

       *  During a remount operation (mount -o remount), the filesystem
          size can be changed (without losing the existing contents of
          the filesystem).

Just wondering what the value of tmpfs is for you instead?

If there was value I could add it as an option to mount using tmpfs instead and modify the tmpdisk manager.

**Comment by TwentyFourD** [comment]
The second item is the bit that makes it most useful for me. I have a service running on my Mac which will run jobs on behalf of other devices on the network. Each job is given its own work directory within the temporary disk I have mounted. Most of the time the process is only using a few kilobytes but every so often a lot of jobs will arrive and it may use up to 16GB. I don't really want to pre-allocate the whole 16GB from memory since it is rare that the whole 16GB is required. OTOH having a max of 2GB available (which is how I used to do it with tmpdisk before finding mount_tmpfs) causes a lot of jobs to fail unnecessarily. Given the amount of churn creating and deleting the work directories and their contents I also don't really want to use my SSD for it either.
Currently I'm running a script to create the tmpfs but I miss the convenience of having tmpdisk automatically manage it for me. It would be nice to have it in tmpdisk but I understand your position, and the script works adequately well, so no pressure :). Thank you for tmdisk regardless.

**Comment by imothee** [comment]
Hi @TwentyFourD - I had to migrate the app to Swift as the code was so outdated I couldn't build it on the latest Xcode so it took a while.

I've added TmpFS as an option for the new TmpDisk alpha - there's two issues
1) It seems to resize your default terminal so if you use iterm and tmux it resizes your terminal
2) The appscript needs sudo access to mount so it needs to have you touch or password the osascript window

https://github.com/imothee/tmpdisk/releases/tag/untagged-92b50a3d520e3a85f1ac

Would love to get your feedback on the feature.

**Comment by TwentyFourD** [comment]
Hey, it's looking good! Thanks :).
The first time I used it, it opened a terminal window, and then the dialog for the password, but since that first time, it now only opens the dialog. I guess it's because I've never used the terminal app on this machine (I use iterm usually).
The folders option is not something I'd use since the work directories I was talking about are all created using mktemp - apologies if I misled you at all and you put that in for me. OTOH, taking advantage of that feature may be a better solution than what I'm currently doing. The mktemp approach does make cleanup easy, though. On the whole I suspect that the folder feature is probably an unnecessary complication, but might well be useful for other use cases than mine. 
The only improvement I can currently think of, is to allow the size to be unspecified for tmpfs which will default the max size to 1/2 your memory (I think...). This works pretty well for me as the memory isn't actually used until you start filling up the disk and it isn't limited unnecessarily. Having said that, I'll only be setting the size once, since I'll be using autocreate (I've already set it up) - so really an unnecessary complication, I guess.
I'm dependent on having a tmpdisk at /Volumes/tmp at the moment so I haven't swapped over to the new version since I don't think you can do that with the new version. As soon as I've converted my apps and scripts I will test more thoroughly, and also do more with the autocreate manager.
I thought about suggesting auto-deleting the mounts on exit but I can definitely see the downside of losing everything from your tmpdisk if you exit accidentally. Having it as an option per mount in the manager might work, but it's a niche requirement at best - I can't imagine it would be worth the effort to add.
As I said, looking good - very good :). I'll get my scripts/apps sorted and do some more testing.

**Comment by TwentyFourD** [comment]
I just noticed that you mentioned iterm being resized specifically. I haven't noticed the resizing but I always resize immediately on open using Rectangle, so I can't say for certain that it isn't affecting me. It didn't affect the one I had open.

**Comment by imothee** [comment]
Re. folders - they've been a feature for a while so wasn't extra work for your use cases.

I was on the fence about polluting /Volumes with folders since they stay and have naming conflicts with non tmpfs tmpdisks which always get mounted into /Volumes.

I'd need to change the way we check whether a folder is mounted since the old method will create a volume and auto rename the folder "tmp 1" which breaks many of the lookups.

I can change it to use /Volumes and just be smarter about naming collisions but since tmpfs needs a physical folder to mount against I had thought putting it in a custom namespace was safer. 

Let me know if the new locations are usable or I can work out how to manager both kinds safely :) 

Thanks for the ram percent size suggestions, I have some ideas there :)

**Comment by imothee** [comment]
Shipped a new version with some minor changes - waiting to hear back in the path issue

**Comment by TwentyFourD** [comment]
I agree with your reasoning about the paths. Keeping them out of /Volumes is a good idea.

**Comment by TwentyFourD** [comment]
I love the %age options :). I've come around to the folders option as well. I'll be using folders to partition between applications (not strictly necessary with mktemp but it'll be a bit more tidy separating them out, and with the folders pre-created it'll be dead easy).
One question, is there any difference using the "hidden" option for tmpfs mounts? I don't see any differences in my usage.
And one minor comment - a few extra percentage options might be useful. I have at least one machine/use case combination where I'd use 75%. Everywhere else I'd use 50% so just that one extra option would be enough for me.
Going back to the location for the tmpfs mount directory, I work pretty much on apps without GUIs (servers, utilities, etc). so I'll mostly be accessing the folder by path. I really like that the path is in the users home directory, and it doesn't really matter whether the folder is hidden or not, but maybe the hidden option could use either .tmpdisk, or tmpdisk (not hidden) as appropriate? Also, is the volumes layer in the ~/.tmpdisk/volumes path there for a reason?
To be honest, other than the 75% option, it's already pretty much perfect for my uses. I'm just desperately trying to find things to comment on to prove I'm actually doing something :).
I haven't had the opportunity see what happens during a new login, or reboot since I can't disconnect from work ATM (one of the downsides of WFH - you're computer is no longer wholly yours) but I'll try and do some testing in that area when I can.

**Comment by TwentyFourD** [comment]
I managed to lock-up my Mac sufficiently often yesterday to test restarts etc. All looks good. Just one potential issue - if I unmount a tmpfs based filesystem which is in the Autocreate Manager, there seems to be no way of remounting it other than restarting the app. Recreate All doesn't seem to do anything with tmpfs based "disks". (A "nice to have" would be the ability to remount individual ones by, e.g., right clicking in the Autocreate Manager)

**Comment by imothee** [comment]
Recreate only recreates mounted disks. I added a (re)create button to the AutoCreate manager that will now recreate or create an AutoCreate disk. LMK if that isn't intuitive and I can change it but I wanted to address the issue at least :)

**Comment by TwentyFourD** [comment]
That's perfect! Functionality is great, so just a minor point - the text on the sub-heading of the "AutoCreate Manager" dialog says "These volumes will be created automatically whenever". Presumably it's missing something like  "tmpDisk starts up" :). 
It works really well now. Way better than I thought it would when I raised the feature request :). Thank you so much for addressing this.
