### ISSUE TITLE
Changed code signature in v 2.0.4?

### ISSUE THREAD

**Issue by suschizu** [imothee/tmpdisk#20]
hey there - I've received a warning that the code signature has changed between version 2.0.3 and 2.0.4 
can you confirm this?

thanks!

`EXPECTED Timothy Marks (R824A4SSXM) but FOUND Timothy Marks (AGZ3AP53DM)`

**Comment by imothee** [comment]
Hi @suschizu - yes, I had to change the developer profile so this is excepted. I tried to do it gradually between 2.0.2 to 2.0.4 so Sparkle would not throw an issue but AGZ3AP53DM is the newest and correct developer profile.

Thanks for checking in.
