### ISSUE TITLE
Feature request: custom icon for new TmpDisk

### ISSUE THREAD

**Issue by ChaG06** [imothee/tmpdisk#21]
Thanks for this great application.

I'd like to be able to specify a custom icon for the newly created TmpDisks.
(Today I just paste it manually in Info window each time)

Regards.

**Comment by imothee** [comment]
Hi @ChaG06 

I've added the requested functionality to an alpha build and would love to hear any feedback or whether this solves your need for setting/managing a custom Volume icon.

https://github.com/imothee/tmpdisk/releases/tag/v2.0.5-alpha

**Comment by ChaG06** [comment]
Hello @imothee 
It works perfectly. This is exactly what I needed.
Thanks a lot.

**Comment by imothee** [comment]
Resolved in 2.0.5
