### ISSUE TITLE
Link to this repository in About window

### ISSUE THREAD

**Issue by zxcat** [imothee/tmpdisk#23]
Will help to find source code and author without googling : )

**Comment by imothee** [comment]
I've done a hacky version of this in 2.0.5 alpha by at least dropping the plaintext url into the string. I'll keep this open to come back with an actual style window or better implementation in the future.

**Comment by zxcat** [comment]
Thanks. Plaintext is good enough for me.

**Comment by imothee** [comment]
Resolved in 2.0.5
