### ISSUE TITLE
Simple Feature Request

### ISSUE THREAD

**Issue by EasyG0ing1** [imothee/tmpdisk#27]
Hello,

It would be nice to have the option of specifying the amount of RAM to use for the disk in Gigabytes as opposed to just Megabytes.

Nice program by the way - very handy!

Thanks,

Mike

**Comment by imothee** [comment]
Have added a dropdown to let you toggle between MB and GB on the NewTmpDisk window in https://github.com/imothee/tmpdisk/releases/tag/v2.0.6-alpha
Would love some extra eyes/testing before I release to the main release channel.

<img width="635" alt="TmpDiskGBSelector" src="https://user-images.githubusercontent.com/574560/219258744-299ca4b0-5356-4ffe-8d50-72011a98e18d.png">

**Comment by EasyG0ing1** [comment]
@imothee Thank you! I'd love to test it, but how do I compile swift code? I've worked heavily with Java and C++ but never Swift.

**Comment by imothee** [comment]
Hi @EasyG0ing1 - I put an alpha release of 2.0.6 up at https://github.com/imothee/tmpdisk/releases/tag/v2.0.6-alpha that includes the disk size changes. You should be able to download and install the new App (and it will autoupdate to the release branch when the new main version is published).

**Comment by EasyG0ing1** [comment]
@imothee - You know I generally consider myself to be somewhat intelligent but right now this isn't making sense to me ... this is what I see at that link and when I download the file all I see in it is source code ... am I missing something?
<img width="585" alt="Screenshot 2023-02-21 at 7 04 49 PM" src="https://user-images.githubusercontent.com/10106834/220511176-20cd716c-21c9-44c7-a6e3-da005526a240.png">

**Comment by imothee** [comment]
Hey @EasyG0ing1 - sorry, not sure what was going on there. For some reason Github said the dmg was corrupt. I re-uploaded the dmg and I can download it at the moment.

<img width="493" alt="Screenshot 2023-02-21 at 7 25 25 PM" src="https://user-images.githubusercontent.com/574560/220513637-83ba5765-1a2a-4fa6-95f5-bbacd3d6a794.png">

**Comment by EasyG0ing1** [comment]
@imothee - Well thank goodness for that, cause I was beginning to think I was losing my mind ... lol .. but that did the trick. Installed and so far working perfectly. 

I suspect, that your software is basically just a GUI interface that sets up the RAM drive then once it's set up, it's not connected to the drive at all ... so like a front end for what would otherwise require terminal commands. 

Am I correct in that regard?

And it's working perfectly. I just love running Windows virtual machines out of ram drives ... something about doing that is very satisfying. lol

**Comment by EasyG0ing1** [comment]
@imothee - After using the modified version for some time now, The only VERY MINOR issue I would comment on is that lets say I create a disk that is 16GB using the new GB option. When I open the program again, it fills the text box with the number 16 but then it defaults back to MB so that if I change it to GB its only a small number that I then need to go back and change to 16.

I realize that its a minor thing, but Im not sure what your personal standards are in terms of the aesthetics in usability for the end user so I thought I would mention it just in case you think something like that should be addressed.

**Comment by clickerpw** [comment]
can you add
1 "default disk name" tmp or temp
2 default size 10%
or use last used config

**Comment by EasyG0ing1** [comment]
I think I would have to say that if we're getting into default names, then that should be defined in a preferences pane and not set to a static name that is always the same for all users. Perhaps even a default size as well should be a settings option.

Wish I knew Swift, I'd write it myself and send a PR if I did.

**Comment by EasyG0ing1** [comment]
@clickerpw - temDisk has an "auto create at startup" checkbox ... and its usually faster to find an app than it is to find a terminal commend to execute ... 
<img width="639" alt="Screenshot 2023-04-14 at 1 47 45 PM" src="https://user-images.githubusercontent.com/10106834/232151892-4f517a2e-bd79-4e77-9882-3ec5016d3296.png">

**Comment by EasyG0ing1** [comment]
@clickerpw Also, there are command line arguments for TmpDisk ... as per the README, 
```BASH
open -a /Applications/TmpDisk.app --args -name=TestDisk -size=64
```
Will create a ramdisk named TestDisk and it will be 64 MB in size.
