### ISSUE TITLE
Recreate Folders after reboot

### ISSUE THREAD

**Issue by shuangg** [imothee/tmpdisk#5]
Is this possible to have an option to recreate certain folders in a RamDisk Volume after reboot?

For now I have to mount 3 Ram disks at boot up. 1 for ~/Library/Caches, 1 for /Library/Caches and 1 for /private/temp. It works but not ideal.

**Comment by gaming-hacker** [comment]
any news on this?

**Comment by imothee** [comment]
Hey,

Ink Scribbles - this projects initial backer and Thin Whiskers no longer exists so I can't use their code signing and I haven't had a chance to sort it out. If there's still interest I'll try and move this over to my account and see if I can get a signed binary built.

**Comment by gaming-hacker** [comment]
cool, i'd like to set up the ram disk on boot and move all of the /private/tmp junk there to thrash away instead of my hard drive.

**Comment by imothee** [comment]
@shuangg and @gaming-hacker 

I have updated the project and created an unsigned binary version
https://github.com/imothee/tmpdisk/releases/tag/v1.1.5-alpha

It has the ability to specify folders to tmpdisks that will be automatically created when the app starts.

I haven't had a chance to work out how the new development signing works for could you test the above and let me know. I'll try to do some testing of my own and work out how to migrate from the Ink Scribbles Account to one of my own.

**Comment by gaming-hacker** [comment]
cool, i'll give it a thrashing.  do you have it configured to be able to run at boot up and create  like /Volumes/Swap/private/tmp?

for this stuff you know it wasn't necessary to sign it?  as long as you a sha1 or some kind of secure hash with it, i'm good with that.

**Comment by imothee** [comment]
I updated the release page, not having it signed means that by default osx won't let you open the app without stepping through some hoops. I'm not sure how technical everyone is so I'd prefer to have it signed for mass distribution.

Wrt your question, yes, if you name your TmpDisk 'Swap' and click autocreate, you can enter

private/tmp

As a folder and when Swap is created on app boot (which you can set to do so on login) it will automatically create

/Volumes/Swap/private/tmp

**Comment by gaming-hacker** [comment]
cool.  
 
oh, Ctrl+click on the app and select Open, pops up a menu,

**Comment by imothee** [comment]
This is now live through the update mechanism as well.
