### ISSUE TITLE
It lives on Sierra!

### ISSUE THREAD

**Issue by SpiraMira** [imothee/tmpdisk#8]
Not really an issue, just an announcement for your interest...

Good work, was looking into iRamDisk and stumbled on this, built it under Sierra PB4 and Xcode 8 beta 5, with very few problems.

Thanks!

**Comment by imothee** [comment]
Thanks @SpiraMira! I've been running it on the Sierra beta but hadn't had a chance to try building it yet. Appreciate the update, I'll add a todo to edit the readme to list supported macOS versions

**Comment by imothee** [comment]
Yeah, this has been the most stable build/program I've maintained for a while. It's so simple that anytime I try and make it better/newer it breaks more :) Glad to hear it's still working for people
