### ISSUE TITLE
Report: Benchmark vs SSD on Retina MBP mid-2015

### ISSUE THREAD

**Issue by replete** [imothee/tmpdisk#9]
Just thought you'd appreciate a benchmark:
RAM on left, SSD on right:

![image](https://cloud.githubusercontent.com/assets/812139/21139072/16b75578-c129-11e6-9b2f-c9fa46dc81b8.png)

Surprisingly, not that noticeable on a typical web project.

**Comment by dasebasto** [comment]
Interesting.

The big boost in uncached read 4k should be noticeable in real world.

Can you notice a difference in your development work?

**Comment by devinrhode2** [comment]
@replete What build tools were you using? Angular cli/webpack/ember? Since these projects may write to disk a few times while transpiling code, I'd expect a decent noticeable performance boost...

**Comment by imothee** [comment]
Closed due to inactivity.

**Comment by replete** [comment]
I must have not had git notifications on 6 years ago!

For the record, at the time of original post I was contracting on an enterprise Angular 1.6 project with a Node backend, I believe that I didn't _notice_ enough mprovement to my particular workflow and abandoned the ram disk idea...

**Comment by replete** [comment]
I just did another test in 2022 on a 13" MBP, npm install on a big project went from 32s to 18s... not a huge improvement
